name: Scrape and Update Iqamah Times

on:
  schedule:
    - cron: '0 9 * * *' # Runs daily at 5 AM EST (9 AM UTC)
  workflow_dispatch: # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Scrape and Update iqamah.json
        run: node scrape.js

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add iqamah.json
          git commit -m "🤖 Update iqamah.json with latest times" || echo "No changes to commit"
          git push
